server:
  port: 4567

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/geenidb
#    username: root
#    password: abc123
#    testWhileIdle: true
#    validationQuery: SELECT 1
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securitydb
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate: error
      springframework:
        web: error
    pro:
      foreway:

client:
  id: 24F0DD1725B3765E7768ECCBF926E363
  key: 1234567890123456